#!/usr/bin/bash

#Ensure you are executing the script from within a git repository.
if git rev-parse --is-inside-work-tree > /dev/null 2>&1; then
  echo "Proceeding with creating a enterprise branch."
else
  echo "This is not a git repository. Please check your path syntax."
  exit
fi

echo "Which release is the enterprise branch for?"
read RELEASE

echo "What JIRA ticket or BZ corresponds to this branch? (e.g., BMPLATFORM-34):"
read JIRA_TICKET

git stash
git checkout --track origin/enterprise-$RELEASE
git fetch upstream enterprise-$RELEASE
git rebase upstream/enterprise-$RELEASE
git switch -c $JIRA_TICKET-$RELEASE
git push --set-upstream origin $JIRA_TICKET-$RELEASE --force
git stash pop
