#!/bin/bash

cd ~/ocp-repos/openshift-docs

if git rev-parse --is-inside-work-tree > /dev/null 2>&1; then
  echo "Proceeding with rebase."
else
  echo "This is not a git repository. Please check your path syntax."
  exit
fi

git stash

CURRENT_BRANCH="$(git branch --show-current)"

if [ $CURRENT_BRANCH != "main" ]; then
     git checkout main >/dev/null 2>&1
     echo "Switching from $CURRENT_BRANCH to main"
fi

git fetch upstream
git rebase upstream/main
git push origin main

if [ $CURRENT_BRANCH != "main" ]; then
    git checkout $CURRENT_BRANCH >/dev/null 2>&1
    echo "Switching from main to $CURRENT_BRANCH"
fi

git stash pop
